### ISSUE TITLE
Error Unauthorized

### ISSUE THREAD

**Issue by garryadkins** [macoirc/tablo_npvr#1]
Hi,

I am new to the Tablo and Jellyfin world, and ran across this project.  I'm a reasonably seasoned developer, so not afraid of a little extra coding.

I tried your python code after making modifications to point to my Tablo 4.  I get the following error:
requests.exceptions.InvalidURL: Failed to parse: http://10.0.251.189:8885error

I tried going directly to the URL you're creating in the python code:
http://10.0.251.189:8885/guide/channels

And I get the following response:
{
error: {
code: "unauthorized",
details: null,
description: "Authentication failure"
}
}

I can't find any decent documentation on how it is expecting authentication (or even what it would use for the credentials).  if you have any documentation, i'd be happy to give it a go.

Alternatively I'm happy to test any code you'd like me to try.

Thanks!

**Comment by macoirc** [comment]
Sorry Garry, I have the Tablo Dual Lite and I just confirmed that it still responds without authentication. My guess is the 4th gen has been redesigned with more restrictions since Tablo makes most of their money from selling you subscription services. You probably have to scour the user forums for Tablo and/or Jellyfin to see if there’s any workaround for the new hardware.

I have actually been using the TabloTV Extra for NextPVR for the past few months and it has been flawless.
